---
_extends: .github

repository:
  name: jvm-macros
  description: Various useful Scala macros
  topics: scala, macros
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci
          - Codacy Static Code Analysis
          - code-review/reviewable
